name: musics-compose
volumes:
  prod_musics:
    driver_opts:
      type: none
      ## CHANGE PATH BELOW FOR YOUR ROOT DIRECTORY ##
      device: '/Volumes/shared/musics'
      o: bind
services:
  musics-nginx:
    image: ghcr.io/zsteinkamp/musics-nginx
    depends_on:
      - musics-web
    ports:
      - '4141:3141'
    restart: unless-stopped
    volumes:
      - prod_musics:/musics:ro
  musics-web:
    image: ghcr.io/zsteinkamp/musics-web
    restart: unless-stopped
    volumes:
      - prod_musics:/musics:ro
