name: musics_prod
services:
  nginx:
    image: nginx:1
    restart: unless-stopped
    ports:
      - "3141:3141"
    volumes:
      - musics:/musics:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
  web:
    build:
      target: prod
    restart: unless-stopped
    volumes:
      - musics:/musics:ro
volumes:
  musics:
    driver: "local"
    driver_opts:
      type: "nfs4"
      o: "addr=10.1.1.2,ro,nfsvers=4"
      device: ":/mnt/data-pool/shared/musics"
