name: musics_dev
services:
  nginx:
    image: nginx:1
    depends_on:
      - web
    ports:
      - '3142:3141'
    stop_signal: SIGKILL
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /mnt/shared/musics:/musics:ro
  web:
    build:
      context: ..
      target: dev
    volumes:
      - ..:/app
      - app_node_modules:/app/node_modules
      - /mnt/shared/musics:/musics:ro
volumes:
  app_node_modules:
